### ISSUE TITLE
Error running server

### ISSUE THREAD

**Issue by zachwise** [NUKnightLab/scenevr-author#21]
Latest commit bfee6d86cc44ef006375fba7c5f5ecd022594c9d throws this error for me.
I added `export USE_LOCAL_STORAGE=True` to the `env.sh`

```
--------------------------------------------------------------------------------
DEBUG in api [app/server/api.py:40]:
config: config.DevConfig
--------------------------------------------------------------------------------
Traceback (most recent call last):
  File "app/server/api.py", line 49, in <module>
    prefix=settings.AWS_STORAGE_KEY_PREFIX)
  File "/Users/zach/Desktop/WebDev/Projects/scenevr-author/app/server/storage.py", line 75, in __init__
    self._bucket = self._conn.get_bucket(bucket)
  File "/Users/zach/.virtualenvs/scenevr-author/lib/python3.7/site-packages/boto/s3/connection.py", line 506, in get_bucket
    return self.head_bucket(bucket_name, headers=headers)
  File "/Users/zach/.virtualenvs/scenevr-author/lib/python3.7/site-packages/boto/s3/connection.py", line 553, in head_bucket
    response.status, response.reason, body)
boto.exception.S3ResponseError: S3ResponseError: 400 Bad Request

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! scenevr-author@1.0.0 server: `python app/server/api.py`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the scenevr-author@1.0.0 server script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/zach/.npm/_logs/2018-07-19T03_30_06_195Z-debug.log
```

**Comment by zachwise** [comment]
Nevermind. forgot to source `env.sh`
