### ISSUE TITLE
Google auth error

### ISSUE THREAD

**Issue by zachwise** [NUKnightLab/scenevr-author#22]
Latest commit causes this
```
builtins.Warning
Warning: Scope has changed from "profile" to "https://www.googleapis.com/auth/userinfo.profile".
Traceback (most recent call last):
  File "/Users/zach/.virtualenvs/scenevr-author/lib/python3.7/site-packages/flask/app.py", line 1997, in __call__
    return self.wsgi_app(environ, start_response)
  File "/Users/zach/.virtualenvs/scenevr-author/lib/python3.7/site-packages/flask/app.py", line 1985, in wsgi_app
    response = self.handle_exception(e)
  File "/Users/zach/.virtualenvs/scenevr-author/lib/python3.7/site-packages/flask/app.py", line 1540, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/zach/.virtualenvs/scenevr-author/lib/python3.7/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/Users/zach/.virtualenvs/scenevr-author/lib/python3.7/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/zach/.virtualenvs/scenevr-author/lib/python3.7/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/zach/.virtualenvs/scenevr-author/lib/python3.7/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/zach/.virtualenvs/scenevr-author/lib/python3.7/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/Users/zach/.virtualenvs/scenevr-author/lib/python3.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/zach/.virtualenvs/scenevr-author/lib/python3.7/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/zach/Desktop/WebDev/Projects/scenevr-author/app/server/api.py", line 472, in google_authorized
    flow.fetch_token(authorization_response=authorization_response)
  File "/Users/zach/.virtualenvs/scenevr-author/lib/python3.7/site-packages/google_auth_oauthlib/flow.py", line 241, in fetch_token
    self.client_config['token_uri'], **kwargs)
  File "/Users/zach/.virtualenvs/scenevr-author/lib/python3.7/site-packages/requests_oauthlib/oauth2_session.py", line 244, in fetch_token
    self._client.parse_request_body_response(r.text, scope=self.scope)
  File "/Users/zach/.virtualenvs/scenevr-author/lib/python3.7/site-packages/oauthlib/oauth2/rfc6749/clients/base.py", line 411, in parse_request_body_response
    self.token = parse_token_response(body, scope=scope)
  File "/Users/zach/.virtualenvs/scenevr-author/lib/python3.7/site-packages/oauthlib/oauth2/rfc6749/parameters.py", line 379, in parse_token_response
    validate_token_parameters(params)
  File "/Users/zach/.virtualenvs/scenevr-author/lib/python3.7/site-packages/oauthlib/oauth2/rfc6749/parameters.py", line 409, in validate_token_parameters
    raise w
Warning: Scope has changed from "profile" to "https://www.googleapis.com/auth/userinfo.profile".
```

**Comment by zachwise** [comment]
OK, got it working. I literally changed `SCOPES=['profile']` to `SCOPES = ['https://www.googleapis.com/auth/userinfo.profile']` line 33 in `api.py`. I’m not sure what the implications of that change might be, but it works now.

**Comment by JoeGermuska** [comment]
i don't remember changing it, and it ought to be the full URL anyway, so if it's working, that's good. When i have more time, maybe I'll look at git blame. thanks.
